### ISSUE TITLE
How to Save Svg without any external Svg? 

### ISSUE THREAD

**Issue by lawrenceong001** [akulmehta/SaveSVG#1]
hello, 

i have some svgs generated as a result of using d3. was trying out your solution, but couldn't figure out the third parameter. the diagram generated by d3 was just a series of shapes and links between them.

**Comment by akulmehta** [comment]
You can leave the third parameter blank then, i.e. do not specify it. It should work. If it does not still work please share a sample page to check.

**Comment by akulmehta** [comment]
@lawrenceong001 have you had the opportunity to try it? If this is resolved please let me know so that I can close the issue. I will close it tomorrow if I don't hear back assuming it worked.

**Comment by lawrenceong001** [comment]
hi @akulmehta, I did try without the 3rd parameter but it didn't work. I ended up using a different library (http://purl.eligrey.com/github/FileSaver.js) to complete the required functionality. but thanks for getting back to me. 

tks
Lawrence

**Comment by akulmehta** [comment]
That is unfortunate that my library didn't work for you. I wish I could have helped more to get it to work. Anyways I will close this issue as I am unable to replicate it without more troubleshooting.
